require("toggleterm").setup {
	open_mapping = [[<c-t>]],
	hide_numbers = true,
	size = 90,
	start_in_insert = true,
	insert_mappings = true,
	terminal_mappings = true,
	persist_size = true,
	persist_mode = true,
	direction = 'vertical',
	close_on_exit = true,
	shell = vim.o.shell,
	auto_scroll = true,
	float_opts = {
		border = "vertical",
		width = 0,
		height = 0,
		winblend = 0,
	},
}
