-- coc 
--local map = vim.api.nvim_set_keymap
--
--map("n", "<F6>", "<Plug>(coc-rename)", { silent = true })
--map("n", "gi", "<Plug>(coc-implementation)", { silent = true })
--
--map("n", "<F3>", "<Plug>(coc-format-selected)", {})
--map("x", "<F3>", "<Plug>(coc-format-selected)", {})
--
--vim.cmd[[
--	inoremap <silent><expr> <TAB> coc#pum#visible() ? coc#pum#confirm()
--								  \: "<Tab>"
--
--	inoremap <silent><expr> <C-SPACE> coc#pum#visible() ? coc#pum#confirm()
--								  \: " "
--
--	inoremap <expr><C-j> coc#pum#visible() ? coc#pum#next(1) : "\<C-j>"
--
--	inoremap <expr><C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-k>"
--]]


--local lsp = require('lsp-zero')
--
--lsp.preset('recommended')
--lsp.nvim_workspace()
--lsp.setup()
