require "user.general"
require "user.plugins"
require "user.colorscheme"
require "user.presence"
require "user.dashboard"
require "user.telescope"
require "user.lualine"
require "user.mappings"
require "user.treesitter"
require "plug-colorizer"

require "user.lsp.language-servers"
