require "impatient"
require "user.general"
require "user.plugins"
require "user.colorscheme"
require "user.presence"
require "user.dashboard"
require "user.telescope"
require "user.lualine"
require "user.mappings"
require "user.treesitter"
require "user.plug-colorizer"
require "user.goyo"
require "user.autocmd"
require "user.indentation"
require "user.navigator"
require "user.toggleterm"

require "user.lsp.language-servers"
