export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="afowler"

gita() {
    git add .
    if [ $1 != "" ] # or better, if [ -n "$1" ]
    then
        git commit -m $1
    else
        git commit -m update
    fi
    git push
}

v() {
    nvim $1
}

# for my sway config
alias idea="_JAVA_AWT_WM_NONREPARENTING=1 ~/.local/bin/idea &"
alias phpstorm="_JAVA_AWT_WM_NONREPARENTING=1 ~/.local/bin/phpstorm &"

alias cat="batcat"

CASE_SENSITIVE="true"

plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh

ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#76b5c5,underline'

function my_init() {
	bindkey '^ ' autosuggest-accept
}
zvm_after_init_commands+=(my_init)

export EDITOR="nvim"
export VISUAL="nvim"

export PATH="$PATH:/home/fabiancodes/.spicetify"
export PATH="$PATH/home/fabiancodes/tools/lua-language-server/bin/Linux:$PATH"
export PATH="$PATH:/home/fabiancodes/.local/bin"
export PATH="$PATH:/home/fabian/.local/bin"

alias ls='exa -lah'
alias ..='cd ..'
#alias vim='nvim'
alias vi='nvim'

alias luamake="$HOME/tools/lua-language-server/3rd/luamake/luamake"

alias cth="nmcli connection up HomeVPN --ask"
alias dfh="nmcli connection down HomeVPN"

# opam configuration
[[ ! -r /home/fabian/.opam/opam-init/init.zsh ]] || source /home/fabian/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

export LC_ALL=de_DE.UTF-8
export LANG=de_DE.UTF-8
